### ISSUE TITLE
Sigil not working with `assert` macro.

### ISSUE THREAD

**Issue by rhnonose** [meyercm/shorter_maps#11] opened 2017-10-12 02:46 UTC
The sigil seems to not be working with `ExUnit`'s `assert` macro.
To reproduce:
```
test "sigil test" do
  assert {:a, ~M{a?: 1, b}} = {:a, %{a?: 1, b: 2}}
  assert b
end
```
It gives the following error:
```
** (CompileError) test/lib/testapp/sigil_test.exs:10: undefined function b/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```
Since `assert` is a macro as well, maybe there's some weird behavior in the macro's compile order.

**Comment by meyercm** [comment] 2017-10-12 12:25
I've just filed elixir-lang/elixir#6925, as my testing seems to show the issue is actually `assert` not preserving the new variables in the corner case you found.  I'll stay on top of that, and update this issue accordingly.

**Comment by rhnonose** [comment] 2017-10-12 12:29
Awesome, thanks for the quick response and analysis.

**Comment by meyercm** [comment] 2018-02-04 20:01
With the release of elixir 1.6, this is now fixed. Let me know if you run into any other problems.  Thanks for the bug report!

**Closed as completed** 2018-02-04 20:12 UTC
